name: Build and release

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'

jobs:
  extract-version:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT


  build-x86_64:
    name: Build for x86_64
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/szbenedek2006/rig-linux:latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build project
        run: |
          make clean
          make ARCH=x86_64 CROSS_COMPILE=

      - name: Compress binaries into .xz
        run: |
          mkdir -p dist
          binary=$(basename bin/*)
          xz -9e -c "bin/$binary" > "dist/${binary}.xz"

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-x86_64-${{ needs.extract_version.outputs.version }}
          path: dist/*.xz # Here the path means each file's path

  build-i686:
    name: Build for i686
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/szbenedek2006/rig-linux:latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build project
        run: |
          make clean
          make ARCH=i686 CROSS_COMPILE=i686-linux-gnu-

      - name: Compress binaries into .xz
        run: |
          mkdir -p dist
          binary=$(basename bin/*)
          xz -9e -c "bin/$binary" > "dist/${binary}.xz"

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-i686-${{ needs.extract_version.outputs.version }}
          path: dist/*.xz # Here the path means each file's path

  build-aarch64:
    name: Build for aarch64
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/szbenedek2006/rig-linux:latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build project
        run: |
          make clean
          make ARCH=aarch64 CROSS_COMPILE=aarch64-linux-gnu-

      - name: Compress binaries into .xz
        run: |
          mkdir -p dist
          binary=$(basename bin/*)
          xz -9e -c "bin/$binary" > "dist/${binary}.xz"

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-aarch64-${{ needs.extract_version.outputs.version }}
          path: dist/*.xz # Here the path means each file's path

  build-armv7l:
    name: Build for armv7l
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/szbenedek2006/rig-linux:latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build project
        run: |
          make clean
          make ARCH=armv7l CROSS_COMPILE=arm-linux-gnueabihf-

      - name: Compress binaries into .xz
        run: |
          mkdir -p dist
          binary=$(basename bin/*)
          xz -9e -c "bin/$binary" > "dist/${binary}.xz"

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-armv7l-${{ needs.extract_version.outputs.version }}
          path: dist/*.xz # Here the path means each file's path


  build-riscv64:
    name: Build for riscv64
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/szbenedek2006/rig-linux:latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build project
        run: |
          make clean
          make ARCH=riscv64 CROSS_COMPILE=riscv64-linux-gnu-

      - name: Compress binaries into .xz
        run: |
          mkdir -p dist
          binary=$(basename bin/*)
          xz -9e -c "bin/$binary" > "dist/${binary}.xz"

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-riscv64-${{ needs.extract_version.outputs.version }}
          path: dist/*.xz # Here the path means each file's path


  release:
    needs: [build-x86_64, build-i686, build-aarch64, build-armv7l, build-riscv64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/ # Directory
          merge-multiple: true

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.extract_version.outputs.version }}
          name: V${{ needs.extract_version.outputs.version }}
          body_path: RELEASE_TEMPLATE.md
          draft: true
          prerelease: false
          files: dist/*.xz
