name: Build and Push Docker Image

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}/rig-linux:latest
          docker build -t $IMAGE .
          docker push $IMAGE

