name: Build and release

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'

jobs:
  extract-version:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT


  build-x86_64:
    name: Build for x86_64
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Build project
        run: |
          make clean
          make ARCH=x86_64 CROSS_COMPILE=
#          make ARCH=riscv64 CROSS_COMPILE=riscv64-linux-gnu-
#          make ARCH=riscv32 CROSS_COMPILE=riscv64-linux-gnu- CFLAGS="-march=rv32imafdc -mabi=ilp32d"

      - name: Compress binaries into tar.xz
        run: |
          mkdir -p dist
          shopt -s nullglob
          for binary in bin/*; do
            base=$(basename "$binary")
            tar -cJf "dist/${base}.tar.xz" -C bin/ "$base"
          done
          shopt -u nullglob

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-x86_64-${{ needs.extract_version.outputs.version }}
          path: dist/*.tar.xz # Here the path means each file's path

  build-i686:
    name: Build for i686
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-i686-linux-gnu


      - name: Build project
        run: |
          make clean
          make ARCH=i686 CROSS_COMPILE=i686-linux-gnu-
#          make ARCH=riscv64 CROSS_COMPILE=riscv64-linux-gnu-
#          make ARCH=riscv32 CROSS_COMPILE=riscv64-linux-gnu- CFLAGS="-march=rv32imafdc -mabi=ilp32d"

      - name: Compress binaries into tar.xz
        run: |
          mkdir -p dist
          shopt -s nullglob
          for binary in bin/*; do
            base=$(basename "$binary")
            tar -cJf "dist/${base}.tar.xz" -C bin/ "$base"
          done
          shopt -u nullglob

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-i686-${{ needs.extract_version.outputs.version }}
          path: dist/*.tar.xz # Here the path means each file's path

  build-aarch64:
    name: Build for aarch64
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu
      - name: Build project
        run: |
          make clean
          make ARCH=aarch64 CROSS_COMPILE=aarch64-linux-gnu-
#          make ARCH=riscv64 CROSS_COMPILE=riscv64-linux-gnu-
#          make ARCH=riscv32 CROSS_COMPILE=riscv64-linux-gnu- CFLAGS="-march=rv32imafdc -mabi=ilp32d"

      - name: Compress binaries into tar.xz
        run: |
          mkdir -p dist
          shopt -s nullglob
          for binary in bin/*; do
            base=$(basename "$binary")
            tar -cJf "dist/${base}.tar.xz" -C bin/ "$base"
          done
          shopt -u nullglob

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-aarch64-${{ needs.extract_version.outputs.version }}
          path: dist/*.tar.xz # Here the path means each file's path

  build-armv7l:
    name: Build for armv7l
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-arm-linux-gnueabihf
      - name: Build project
        run: |
          make clean
          make ARCH=armv7l CROSS_COMPILE=arm-linux-gnueabihf-
#          make ARCH=riscv64 CROSS_COMPILE=riscv64-linux-gnu-
#          make ARCH=riscv32 CROSS_COMPILE=riscv64-linux-gnu- CFLAGS="-march=rv32imafdc -mabi=ilp32d"

      - name: Compress binaries into tar.xz
        run: |
          mkdir -p dist
          shopt -s nullglob
          for binary in bin/*; do
            base=$(basename "$binary")
            tar -cJf "dist/${base}.tar.xz" -C bin/ "$base"
          done
          shopt -u nullglob

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: RIG-armv7l-${{ needs.extract_version.outputs.version }}
          path: dist/*.tar.xz # Here the path means each file's path




  release:
    needs: [build-x86_64, build-i686, build-aarch64, build-armv7l]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/ # Directory
          merge-multiple: true

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.extract_version.outputs.version }}
          name: V${{ needs.extract_version.outputs.version }}
          body_path: RELEASE_TEMPLATE.md
          #body: |
          #  # My first automated build and release
          #  **This is a test version, stay on the 2.4.1 version released on Apr 10!**
          draft: true
          prerelease: false
          files: dist/*.tar.xz
