name: C/C++ CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    container:
      image: IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}:latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential && cat /etc/os-release

    - name: make ARCH=x86_64
      run: make

    - name: make clean
      run: make clean

  build-i686:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc-i686-linux-gnu

    - name: make
      run: make ARCH=i686 CROSS_COMPILE=i686-linux-gnu-

    - name: make clean
      run: make clean

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc-aarch64-linux-gnu

    - name: make ARCH=aarch64 CROSS_COMPILE=aarch64-linux-gnu-
      run: make

    - name: make clean
      run: make clean

  build-armv7l:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc-arm-linux-gnueabihf

    - name: make ARCH=armv7l CROSS_COMPILE=arm-linux-gnueabihf-
      run: make

    - name: make clean
      run: make clean

